apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-simple.fullname" .}}
  labels:
{{ include "nginx-simple.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
  selector:
    app.kubernetes.io/name: {{ include "nginx-simple.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

   


