apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql-single.fullname" . }}
  labels:
{{ include "mysql-single.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    app.kubernetes.io/name: {{ include "mysql-single.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
